### ISSUE TITLE
Can not login with RealDebrid

### ISSUE THREAD

**Issue by amcgready** [debridmediamanager/debrid-media-manager#111]
This error seems to be happening again and real-debrid login is broken. Attaching a screenshot of the error.
![Screenshot 2024-03-30 131811](https://github.com/debridmediamanager/debrid-media-manager/assets/63322021/e0e79af3-0e2a-4bd8-aac0-092253319223)

**Comment by Badn1nja** [comment]
There was a fault yesterday - should be back now

**Comment by yowmamasita** [comment]
It should be fixed now. If you're still having issues, check this post

https://www.reddit.com/r/debridmediamanager/comments/1bslwxu/if_you_are_stuck_on_loading_screen_click_clear/
