### ISSUE TITLE
[Request] Collapsible Lists

### ISSUE THREAD

**Issue by amcgready** [debridmediamanager/debrid-media-manager#114]
I have a large number of lists on Trakt containing literally thousands of films. It would be great if there was the ability to collapse each list by clicking on the list name. Ideally, if there is a way to permanently select which lists show that would be ideal. I have lists for studios and don't see much of a need for using those lists in DMM.

**Comment by yowmamasita** [comment]
Somebody requested this and it's on a branch right now, just isn't finished yet. Will do it!

**Comment by andbladi** [comment]
So exciting to hear this is in the works! And not to get too greedy, but any chance there'll ever a be a feature to have DMM add cached films automatically from a given Trakt list (based on a simple quality profile)?

**Comment by yowmamasita** [comment]
This is implemented in a way where every list gets its own page
