### ISSUE TITLE
Access to Trakt collection

### ISSUE THREAD

**Issue by The-Droidster** [debridmediamanager/debrid-media-manager#117]
Would it be possible to add the user's Trakt collection under https://debridmediamanager.com/trakt/movies along with the popular Trakt lists?

**Comment by yowmamasita** [comment]
what is this user's trakt collection? or are you referring to the personal lists you have on trakt?

**Comment by healy93** [comment]
I was wondering the same thing. I don't use lists, but I have a collection of about 500 films and 1,200 TV shows since 2016. I would love to put them on RD so they sync over to Plex via Zurg.

**Comment by yowmamasita** [comment]
This is now implemented! https://www.patreon.com/posts/dmm-updates-114511349
