### ISSUE TITLE
[Feature Request] Auto scheduling Reinsert

### ISSUE THREAD

**Issue by trulow** [debridmediamanager/debrid-media-manager#124]
The reinsert feature is great but it would be nice if we could possibly set up a schedule so it can automatically reinsert certain links to prevent it from expiring after X amount of time.

Are there any current plans to implement such a feature?

**Comment by yowmamasita** [comment]
Honestly, I don’t think it’s a good idea to aggressively use this feature to manipulate Real-Debrid’s caching. Real-Debrid has limited storage for cached content. If everyone starts frequently refreshing their content, it could lead to storage issues and potentially degrade caching performance overall. We shouldn’t be greedy about these things.

Furthermore, implementing such a feature could encourage misuse and strain Real-Debrid’s resources, possibly resulting in stricter policies or limitations. It’s better to use the service responsibly to ensure it remains efficient for everyone.
