### ISSUE TITLE
Show which Hashlist torrent titles are already in library

### ISSUE THREAD

**Issue by Nosh118** [debridmediamanager/debrid-media-manager#127]
Provide an option to show which of the torrents in a hashlist have their title already in the user's library.

Also provide option to filter by those in or not in the library

**Comment by yowmamasita** [comment]
The torrents already in your library are hidden in a given hashlist

![image](https://github.com/debridmediamanager/debrid-media-manager/assets/1567724/d32f887d-20d1-473d-b782-39e1fae08116)

This is determined by hash.

The workflow for same titles should be add them in your library first and then use the utilities in your library to dedupe titles, etc.

**Comment by Nosh118** [comment]
Ah okay, this just seems like an intense workflow for larger libraries.

thank you though!
