### ISSUE TITLE
Add built in sharing of curated hash lists

### ISSUE THREAD

**Issue by Nosh118** [debridmediamanager/debrid-media-manager#128]
Be able to publish hashlists publicly with titles and curation for others to easily add

**Comment by yowmamasita** [comment]
Can you detail out what you mean by "curation"?

**Comment by Nosh118** [comment]
So for example people could publish lists titled things like:

Top 100 films according to IMDB (4K x265)

and a user would be able to easily browse them and pick ones they would like

**Comment by yowmamasita** [comment]
https://www.patreon.com/posts/dmm-updates-114511349 it is now possible to add titles
