### ISSUE TITLE
How can I automatically share my "share list"?

### ISSUE THREAD

**Issue by Telkaoss** [debridmediamanager/debrid-media-manager#133]
I am writing a Python script that retrieves Jackett queries from a public self-hosted Stremio addon and sends them to my Real-Debrid API. I want to be able to automatically share them on DMM.

**Comment by CaptainQuinn** [comment]
Such option would be nice to have, and if enabled by default DMM's user would automaticaly increase public hashlist after each add : DMM research/zilean could even replace trackers.

We are looking for such solution because it is more difficult to have non english (French audio) quality torrents as the main french tracker is private/protected by Cloudflare/not API friendly/entry fee.

**Comment by Telkaoss** [comment]
How to check if the library is properly shared? I'm stuck on this page.

![Uploading Screenshot_20240824-022258.png…]()

**Comment by CaptainQuinn** [comment]
> How to check if the library is properly shared? I'm stuck on this page.
> click here for spoil
> 
> ![Screenshot_20240824-022258](https://private-user-images.githubusercontent.com/159430099/361088882-5be41415-7997-42d4-8261-b4ebf10dec4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0OTAwNjAsIm5iZiI6MTcyNDQ4OTc2MCwicGF0aCI6Ii8xNTk0MzAwOTkvMzYxMDg4ODgyLTViZTQxNDE1LTc5OTctNDJkNC04MjYxLWI0ZWJmMTBkZWM0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwODU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmJlNzU2MmIwMzk2OTFhNzZhNmU0YTlmYmNjZmY4YzdkNTkyYWU5M2Q2NmJjNjcyMTkzODkxZTVkYmRmZTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kfoAHrzjJdB6eSEi2yu4PXkbWhNf2kruqWeSqlJiqxQ)

Yesterday mine was just way longer than a few minutes to process, but check again its link in your browser history it should now be shared

**Comment by yowmamasita** [comment]
im sorry but all hashlists are stored on my github repo and that means giving you write access to do this

i'm also not ok with enabling this for all users
