### ISSUE TITLE
TorBox API Error: Network Error. Status: unknown

### ISSUE THREAD

**Issue by Pietro395** [debridmediamanager/debrid-media-manager#139]
Saving API Key for TorBox I get the error “API Error: Network Error. Status: unknown”.

![image](https://github.com/user-attachments/assets/52e3cd8a-665b-4571-be82-d7e83dce72cb)

Looking at the requests on the browser the API returns error "400: Bad request":
https://api.torbox.app/v1/api/user/me?settings=false

![image](https://github.com/user-attachments/assets/312edd5a-1c54-40da-9835-aa756875828a)

**Comment by yowmamasita** [comment]
I will announce when Torbox integration is fully working. For now, consider everything to be broken
