### ISSUE TITLE
Can't Log In with Real-Debrid

### ISSUE THREAD

**Issue by scoopersondooperson** [debridmediamanager/debrid-media-manager#140]
I can't seem to log in with Real-Debrid. After cliciking the button to authorize with RD, the DBMM page doesn't update and just sits on the page asking me to click the button. 

The only explanation I can find is that there's a message in the browser's console about an error with a POST request to https://proxy.debridmediamanager.com/anticors?url=https://api.real-debrid.com/oauth/v2/token. It just says error 400 (Bad Request.

**Comment by umair-me** [comment]
I am having same issue. Entering code again on RD return error with invalid code.

**Comment by yowmamasita** [comment]
Should be fixed now :) Thanks for reporting
