### ISSUE TITLE
Wont show RD Contents

### ISSUE THREAD

**Issue by Dexxa1024** [debridmediamanager/debrid-media-manager#48]
I've been trying to use the site but having no luck

I've linked it to my RD and when i go to the main page to view my torrents all im getting is Error fetching user torrents list

But i can add torrents to RD By hashtages

How do i go about fixing the Error fetching user torrents list and it get it to show my torrents from my RD Account,

Also tried to install via Docker, But cant seem to get it to even install, Tried the instructions on the github but i dont know them commands

Anyway easy way for a new person to get this installed?

Thanks

**Comment by machetie** [comment]
i have the same issue looking for solutions to view to the content too. haven't tried installing locally yet.

**Comment by yowmamasita** [comment]
Hey I wasn't checking the issues so I wasn't able to respond immediately. Let me see what I can do given the limited information.

**Comment by yowmamasita** [comment]
Can you please show me the output of this page

https://debridmediamanager.com/troubleshooting

**Comment by AnonEstranho** [comment]
Hello there. I have the same problem. Here is the troubleshooting page input:

`Running test...
-----
Real-Debrid cached downloads: 351
Real-Debrid refreshed downloads: 0
-----
AllDebrid cached downloads: 0
AllDebrid refreshed downloads: 0
-----
Real-Debrid base URL: https://corsproxy.org/?https://api.real-debrid.com
RD torrent count: 2122
-----
Real-Debrid base URL: https://corsproxy.io/?https://api.real-debrid.com
RD torrent count: 2122
-----
Real-Debrid base URL: https://api.real-debrid.com
RD torrent error: AxiosError: Network Error
-----
Test complete!`
