### ISSUE TITLE
Error RD restore

### ISSUE THREAD

**Issue by balajiselva** [debridmediamanager/debrid-media-manager#99]
I tried to restore my backup, but it failed 
[backup-1704547429506.dmm.json](https://github.com/debridmediamanager/debrid-media-manager/files/13856288/backup-1704547429506.dmm.json)

**Comment by yowmamasita** [comment]
what's the error? any screenshots?

**Comment by balajiselva** [comment]
https://drive.google.com/file/d/1DgZX9jdrHFf63QyXHRVFJZYWZ-scXBjl/view?usp=drivesdk


Have a look

**Comment by y0ungee** [comment]
Yep, mine failed too!

**Comment by yowmamasita** [comment]
Fix incoming! Apologies for the late response
